### ISSUE TITLE
File tree brakes when folder icon is changed

### ISSUE THREAD

**Issue by jamran7** [ChainsawFist/brackets#2]
[file_tree_breaks_on_OSX_when_folder_with_folder_icon_is_used_Issue_12789_adobe_brackets.pdf](https://github.com/ChainsawFist/brackets/files/488645/file_tree_breaks_on_OSX_when_folder_with_folder_icon_is_used_Issue_12789_adobe_brackets.pdf)

**Comment by jamran7** [comment]
adobe link:
https://github.com/adobe/brackets/issues/12789

**Comment by jamran7** [comment]
This has been 80% fixed; the project model inside project/ProjectModel.js now hides folders and file names that strictly have the name "Icon" when the file cache is initialized. "Icons", "Icon?", "Icon.js" is currently allowed and does not break the file tree. What is left is that when the file cache is initialize, there needs to be a way to determine if the path is physically a directory despite the fact that everything is initially a file.

**Comment by ghost** [comment]
This issue is now closed with the pull request #11 This solution uses a regex to ignore only the Icon\r file and not folders named Icon
