### ISSUE TITLE
Brackets turns into a web browser when you drag a url link into the editor

### ISSUE THREAD

**Issue by jamran7** [ChainsawFist/brackets#3]
[Brackets_turns_into_a_web_browser_Issue_12441_adobe_brackets.pdf](https://github.com/ChainsawFist/brackets/files/488647/Brackets_turns_into_a_web_browser_Issue_12441_adobe_brackets.pdf)

**Comment by jamran7** [comment]
adobe link:
https://github.com/adobe/brackets/issues/12441

**Comment by ghost** [comment]
Solution has been published. Default behavior was only being stopped if the dragged item was a file, the default needed to be stopped for all items being dragged and each item handled as it was expected to be handled by the program. #8

**Comment by boycepoleonjr** [comment]
Still open in main. So all that needs to be done is write up the pull request.
