### ISSUE TITLE
File tree brakes after filename interference

### ISSUE THREAD

**Issue by jamran7** [ChainsawFist/brackets#4]
[File-tree_crashes_after_filename_interference_problems_Issue_12462_adobe_brackets (1).pdf](https://github.com/ChainsawFist/brackets/files/488650/File-tree_crashes_after_filename_interference_problems_Issue_12462_adobe_brackets.1.pdf)

**Comment by jamran7** [comment]
adobe link:
https://github.com/adobe/brackets/issues/12462

**Comment by jamran7** [comment]
bpoleonjr is currently working on this bug.

**Comment by boycepoleonjr** [comment]
Still open in main.

**Comment by boycepoleonjr** [comment]
# Issue fixed.

Line added in doCreate() method;
**" var fs = _getFSObject(path); "**
This line refreshes the cache by updating the path.
