### ISSUE TITLE
Text disappears after a certain number of tab indents when word wrap is enabled

### ISSUE THREAD

**Issue by jamran7** [ChainsawFist/brackets#5]
[Word_wrap_indentation_may_show_nothing_at_all_Issue_12178_adobe_brackets.pdf](https://github.com/ChainsawFist/brackets/files/488655/Word_wrap_indentation_may_show_nothing_at_all_Issue_12178_adobe_brackets.pdf)

adobe link:
https://github.com/adobe/brackets/issues/12178

**Comment by jamran7** [comment]
clindelof is working on this bug.

**Comment by ghost** [comment]
See #10 for solution. This issue is now closed

**Comment by boycepoleonjr** [comment]
Still open in main. So all that needs to be done is write up the pull request.
