### ISSUE TITLE
Issue with Mac OS bonk sound when using command to move line of text down

### ISSUE THREAD

**Issue by jamran7** [ChainsawFist/brackets#6]
[Mac__Bonk_beep_sound_when_pressing_CMD-Ctrl-Down_in_an_editor_Issue_2419_adobe_brackets (1).pdf](https://github.com/ChainsawFist/brackets/files/488668/Mac__Bonk_beep_sound_when_pressing_CMD-Ctrl-Down_in_an_editor_Issue_2419_adobe_brackets.1.pdf)

adobe link:
https://github.com/adobe/brackets/issues/2419

**Comment by jamran7** [comment]
lnadur is currently working on this bug.

**Comment by boycepoleonjr** [comment]
Not a brackets issue. Closing issue.

**Comment by lnadur** [comment]
This is an issue across different programs not just brackets.  We believe it may be a chromium issue.  For this reason we decided to drop this issue.
