### ISSUE TITLE
Opening a minified file in Brackets slows down the performance of the editor.

### ISSUE THREAD

**Issue by jamran7** [ChainsawFist/brackets#7]
[Open file with one line type very slow · Issue #12678 · adobe_brackets.pdf](https://github.com/ChainsawFist/brackets/files/488671/Open.file.with.one.line.type.very.slow.Issue.12678.adobe_brackets.pdf)

adobe link:
https://github.com/adobe/brackets/issues/12678

**Comment by boycepoleonjr** [comment]
Still open in main.

**Comment by lnadur** [comment]
After further testing, we determined that this did not slow down the performance of the editor by very much, and wasn't necessary to fix.
